media: src/assets
content:
  - name: courses
    label: Courses
    type: collection
    path: 'src/data/courses&services/Courses'
    view:
      fields: [ title, description, order ]
    fields:
    - name: title
      label: Title
      type: string
      required: true
    - name: description
      label: Card Description
      type: rich-text
      required: true
    - name: heroImage
      label: Hero Image (Big image at the back)
      type: image
      required: true
    - name: sub
      label: Main Page Sub Heading
      type: rich-text
      required: true
    - name: header
      label: Header Image (for cards)
      type: image
      required: true
    # - name: images
    #   label: Other Images
    #   type: object
    #   list: true
    #   fields:
    #     - name: internal
    #       label: Image Group
    #       type: image
    #       list: 
    #         min: 3
    #         max: 3
    - name: order
      label: Order of Posts (Services, Courses, professional Courses)
      type: number
      required: true
    - name: body
      label: Page Content (The actual writing in the page)
      type: text

  
  - name: professional_courses
    label: Professional Courses
    type: collection
    path: 'src/data/courses&services/Professional Courses'
    view:
      fields: [ title, description, order ]
    fields:
    - name: title
      label: Title
      type: string
      required: true
    - name: description
      label: Card Description
      type: rich-text
      required: true
    - name: heroImage
      label: Hero Image (Big image at the back)
      type: image
      required: true
    - name: sub
      label: Main Page Sub Heading
      type: rich-text
      required: true
    - name: header
      label: Header Image (for cards)
      type: image
      required: true
    # - name: images
    #   label: Other Images
    #   type: image
    #   list: true
      required: true
    - name: order
      label: Order of Posts (Services, Courses, professional Courses)
      type: number
      required: true
    - name: body
      label: Page Content (The actual writing in the page)
      type: text


  - name: services
    label: Services
    type: collection
    path: 'src/data/courses&services/Services'
    view:
      fields: [ title, description, order ]
    fields:
    - name: title
      label: Title
      type: string
      required: true
    - name: description
      label: Card Description
      type: rich-text
      required: true
    - name: heroImage
      label: Hero Image (Big image at the back)
      type: image
      required: true
    - name: sub
      label: Main Page Sub Heading
      type: rich-text
      required: true
    - name: header
      label: Header Image (for cards)
      type: image
      required: true
    # - name: images
    #   label: Other Images
    #   type: image
    #   list: true
    #   required: true
    - name: order
      label: Order of Posts (Services, Courses, professional Courses)
      type: number
      required: true
    - name: body
      label: Page Content (The actual writing in the page)
      type: text

  - name: store
    label: Store
    type: collection
    path: 'src/data/store'
    view:
      fields: [ title, description, order ]
    fields:
    - name: title
      label: Title
      type: string
      required: true
    - name: description
      label: Card Description
      type: rich-text
      required: true
    - name: header
      label: Header Image (for cards)
      type: image
      required: true
    - name: images
      label: Other Images
      type: image
      list: true
    - name: order
      label: Order of Posts (Services, Courses, professional Courses)
      type: number
      required: true
    - name: draft
      label: Do you want to publish this page?
      type: boolean
      required: true
    - name: body
      label: Page Content (The actual writing in the page)
      type: text