media: src/assets
content:
  - name: courses
    label: Courses
    type: collection
    path: 'src/data/courses&services/Courses'
    view:
      fields: [ title, description, order ]
    fields:
    - name: title
      label: Title
      type: string
    - name: description
      label: Card Description
      type: rich-text
    - name: heroImage
      label: Hero Image (Big image at the back)
      type: image
    - name: sub
      label: Main Page Sub Heading
      type: rich-text
    - name: header
      label: Header Image (for cards)
      type: image
    - name: images
      label: Other Images
      type: image
      list: true
    - name: order
      label: Order of Posts (Services, Courses, professional Courses)
      type: number

  - name: professional_courses
    label: Professional Courses
    type: collection
    path: 'src/data/courses&services/Professional Courses'
    view:
      fields: [ title, description, order ]
    fields:
    - name: title
      label: Title
      type: string
    - name: description
      label: Card Description
      type: rich-text
    - name: heroImage
      label: Hero Image (Big image at the back)
      type: image
    - name: sub
      label: Main Page Sub Heading
      type: rich-text
    - name: header
      label: Header Image (for cards)
      type: image
    - name: images
      label: Other Images
      type: image
      list: true
    - name: order
      label: Order of Posts (Services, Courses, professional Courses)
      type: number


  - name: services
    label: Services
    type: collection
    path: 'src/data/courses&services/Services'
    view:
      fields: [ title, description, order ]
    fields:
    - name: title
      label: Title
      type: string
    - name: description
      label: Card Description
      type: rich-text
    - name: heroImage
      label: Hero Image (Big image at the back)
      type: image
    - name: sub
      label: Main Page Sub Heading
      type: rich-text
    - name: header
      label: Header Image (for cards)
      type: image
    - name: images
      label: Other Images
      type: image
      list: true
    - name: order
      label: Order of Posts (Services, Courses, professional Courses)
      type: number